# Generated by Django 6.0.4 on 2026-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_licenseactivationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('queued', 'Queued')], default='running', max_length=10),
        ),
    ]
